apiVersion: apps/v1
kind: Deployment
metadata:
  name: py_server
  lables:
    app: test
spec:
  replicas: 2
  selector:
    matchLables:
      app: test
  template:
    metadata:
      name: python-server
    spec:
      containers:
      - name: app
        image: kakaru0/python_server:latest
        ports:
        - containerPort: 8000
    
  
