apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server_replica
  labels:
    app: server
    release: server-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
    template:
      metadata:
        labels:
          app: test
        spec:
          containers:
          - name: app
            image: kakaru0/python_server:latest
            ports:
            - containerPort: 8000